import React from 'react'

export const Aboutus = () => {
  return (
    <>
    <h1>Welcome to About Page</h1>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores et possimus iusto quisquam impedit qui nisi mollitia, eveniet, necessitatibus veniam harum sit. Libero, fugit! Fugit doloribus aperiam, adipisci beatae quibusdam distinctio id at dolorem quam, ea iusto natus tempore! Totam nemo illum obcaecati eligendi esse numquam, voluptatem nam eos rem. Incidunt cumque sit facilis. Quis facere aut reiciendis dolorum in inventore porro quos quisquam voluptatibus harum eum nobis, vitae, similique accusamus saepe officiis? Libero debitis error quo nemo rerum quibusdam tenetur perferendis optio obcaecati, minima corporis expedita, iure reprehenderit id, quis eius perspiciatis? Dolores, recusandae quis quae beatae exercitationem neque aperiam molestias sunt! Possimus amet harum perspiciatis aliquam, sequi quos doloribus eligendi dolorum, sit tenetur laboriosam odit libero quod debitis quaerat qui. Cum enim odit sapiente, hic perspiciatis veniam omnis architecto. Tempore alias quibusdam esse, eum sed id reiciendis velit eaque similique nesciunt perferendis, quaerat sit nisi veritatis facilis enim ullam consequatur debitis quas necessitatibus odit corrupti! Ab nesciunt officiis provident ipsam suscipit illum doloremque necessitatibus eaque inventore magnam non ut assumenda saepe qui harum consectetur autem, debitis error, aliquam dolorem vero vitae dignissimos animi deleniti? Nostrum perspiciatis est, modi dolorem aspernatur eos, voluptatem vero quo dolorum tempora corrupti numquam cupiditate odio reprehenderit labore beatae quibusdam similique. Amet quis reiciendis dignissimos ut odio laboriosam modi, omnis a labore ad corrupti expedita beatae asperiores dolorum et repellendus debitis? Assumenda voluptas, quisquam nesciunt accusamus ad doloribus rerum placeat, deserunt maxime voluptates harum dolores porro provident facere voluptatum, at eligendi adipisci explicabo corrupti ex accusantium sapiente earum voluptatem? Aliquam distinctio dolor omnis culpa accusamus ullam cumque tempore nihil doloribus! Officiis omnis quos beatae modi eius consectetur enim natus aperiam, et nostrum libero necessitatibus odio repellendus dignissimos sunt aut inventore commodi magni ducimus explicabo quaerat iste. Quisquam nostrum incidunt modi, sunt facere dolores id?</p>
    </>
  )
}
